/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.JogosGvo;
import bean.PatrocinadoresGvo;
import bean.PlataformaGvo;
import dao.Jogos_DAO;
import dao.Patrocinadores_DAO;
import dao.Plataforma_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import tools.Util;

/**
 *
 * @author Guilherme132BR
 */
public class JDlgJogosIA extends javax.swing.JDialog {

    /**
     * Creates new form JDlgJogosIA
     */
    public JDlgJogosIA(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
      public JogosGvo viewBean() {
        JogosGvo jogosGvo = new JogosGvo();

        jogosGvo.setNomeGvo(jTxtTituloJogo.getText());
        jogosGvo.setVersaoFisicaGvo(jTxtVersaoFisica.getText());
        jogosGvo.setPrecoGvo(Util.strDouble(jFmtPreco.getText()));
        jogosGvo.setIdJogosGvo(Util.strInt(jFmtIdJogos.getText()));
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        try
        {
            jogosGvo.setDataLancamentoGvo(formato.parse(jFmtDataLancamento.getText()));
        } catch (ParseException ex)
        {
            System.out.println("Erro" + ex.getMessage());
        }
        PatrocinadoresGvo patrocinadores1 = (PatrocinadoresGvo) jCboPatrocinadores.getSelectedItem();
        jogosGvo.setPatrocinadoresGvo(patrocinadores1.getIdPatrocinadoresGvo());

        PlataformaGvo plataforma1 = (PlataformaGvo) jCboPlat.getSelectedItem();
        jogosGvo.setPlataformaGvo(plataforma1.getIdPlataformaGvo());

        return jogosGvo;};
      
      public void beanView(JogosGvo jogosGvo) {

        String id = String.valueOf(jogosGvo.getIdJogosGvo());
        jFmtIdJogos.setText(id);
        jTxtTituloJogo.setText(jogosGvo.getNomeGvo());
        jTxtVersaoFisica.setText(jogosGvo.getVersaoFisicaGvo());
        jFmtPreco.setText(Util.doubleStr(jogosGvo.getPrecoGvo()));
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        jFmtDataLancamento.setText(formato.format(jogosGvo.getDataLancamentoGvo()));

        int idPlataformaGvo = jogosGvo.getPlataformaGvo();
        Plataforma_DAO plataforma_DAO = new Plataforma_DAO();
        jCboPlat.setSelectedItem((PlataformaGvo) plataforma_DAO.list(idPlataformaGvo));

        int idPatrocinadoresGvo = jogosGvo.getPatrocinadoresGvo();
        Patrocinadores_DAO patrocinadores_DAO = new Patrocinadores_DAO();
        jCboPatrocinadores.setSelectedItem((PatrocinadoresGvo) patrocinadores_DAO.list(idPatrocinadoresGvo));

    }
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnOk = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTxtTituloJogo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFmtPreco = new javax.swing.JFormattedTextField();
        jFmtDataLancamento = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jCboPlat = new javax.swing.JComboBox<PlataformaGvo>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTxtVersaoFisica = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jFmtIdJogos = new javax.swing.JFormattedTextField();
        jCboPatrocinadores = new javax.swing.JComboBox<PatrocinadoresGvo>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jBtnOk.setText("Ok");
        jBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOkActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOk);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCancelar);

        jLabel2.setText("Título do Jogo");

        jTxtTituloJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTituloJogoActionPerformed(evt);
            }
        });

        jLabel8.setText("Patrocinadores");

        jLabel5.setText("Data de Lançamento");

        jCboPlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPlatActionPerformed(evt);
            }
        });

        jLabel3.setText("versão física");

        jLabel7.setText("Plataforma");

        jTxtVersaoFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtVersaoFisicaActionPerformed(evt);
            }
        });

        jLabel1.setText("IdJogos");

        jFmtIdJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtIdJogosActionPerformed(evt);
            }
        });

        jCboPatrocinadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboPatrocinadoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jCboPlat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel5)
                                .addComponent(jFmtDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCboPatrocinadores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtTituloJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jFmtIdJogos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(67, 67, 67)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTxtVersaoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtTituloJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtVersaoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFmtIdJogos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCboPlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboPatrocinadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtDataLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jFmtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOkActionPerformed
        // TODO add your handling code here:
    JogosGvo jogosGvo = viewBean();
    Jogos_DAO jogos_DAO = new Jogos_DAO();
    jogos_DAO.insert(jogosGvo);
    
    Util.limparCampos(jTxtTituloJogo, jCboPatrocinadores, jCboPlat, jFmtDataLancamento, jFmtIdJogos, jFmtPreco, jTxtVersaoFisica);
    Util.mensagem("incluido");
    }//GEN-LAST:event_jBtnOkActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtTituloJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTituloJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTituloJogoActionPerformed

    private void jCboPlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboPlatActionPerformed

    private void jTxtVersaoFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtVersaoFisicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtVersaoFisicaActionPerformed

    private void jFmtIdJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtIdJogosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtIdJogosActionPerformed

    private void jCboPatrocinadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboPatrocinadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboPatrocinadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgJogosIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgJogosIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgJogosIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgJogosIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgJogosIA dialog = new JDlgJogosIA(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOk;
    private javax.swing.JComboBox<PatrocinadoresGvo> jCboPatrocinadores;
    private javax.swing.JComboBox<PlataformaGvo> jCboPlat;
    private javax.swing.JFormattedTextField jFmtDataLancamento;
    private javax.swing.JFormattedTextField jFmtIdJogos;
    private javax.swing.JFormattedTextField jFmtPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtTituloJogo;
    private javax.swing.JTextField jTxtVersaoFisica;
    // End of variables declaration//GEN-END:variables
}
