package bean;
// Generated 21/09/2023 21:37:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClienteGvo generated by hbm2java
 */
@Entity
@Table(name="cliente_gvo"
    ,catalog="guilherme_osterberg2"
)
public class ClienteGvo  implements java.io.Serializable {


     private int idclienteGvo;
     private UsuariosGvo usuariosGvo;
     private String nome;
     private String sobreNome;
     private String cpf;
     private String endereco;
     private String pais;
     private String bairro;
     private String cidade;
     private String telefone;
     private String celular;
     private String desconto;
     private Set comprasGvos = new HashSet(0);

    public ClienteGvo() {
    }

	
    public ClienteGvo(int idclienteGvo, UsuariosGvo usuariosGvo, String nome, String sobreNome, String cpf, String endereco, String pais, String bairro, String cidade, String celular, String desconto) {
        this.idclienteGvo = idclienteGvo;
        this.usuariosGvo = usuariosGvo;
        this.nome = nome;
        this.sobreNome = sobreNome;
        this.cpf = cpf;
        this.endereco = endereco;
        this.pais = pais;
        this.bairro = bairro;
        this.cidade = cidade;
        this.celular = celular;
        this.desconto = desconto;
    }
    public ClienteGvo(int idclienteGvo, UsuariosGvo usuariosGvo, String nome, String sobreNome, String cpf, String endereco, String pais, String bairro, String cidade, String telefone, String celular, String desconto, Set comprasGvos) {
       this.idclienteGvo = idclienteGvo;
       this.usuariosGvo = usuariosGvo;
       this.nome = nome;
       this.sobreNome = sobreNome;
       this.cpf = cpf;
       this.endereco = endereco;
       this.pais = pais;
       this.bairro = bairro;
       this.cidade = cidade;
       this.telefone = telefone;
       this.celular = celular;
       this.desconto = desconto;
       this.comprasGvos = comprasGvos;
    }
   
     @Id 

    
    @Column(name="idcliente_gvo", unique=true, nullable=false)
    public int getIdclienteGvo() {
        return this.idclienteGvo;
    }
    
    public void setIdclienteGvo(int idclienteGvo) {
        this.idclienteGvo = idclienteGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Usuarios_gvo", nullable=false)
    public UsuariosGvo getUsuariosGvo() {
        return this.usuariosGvo;
    }
    
    public void setUsuariosGvo(UsuariosGvo usuariosGvo) {
        this.usuariosGvo = usuariosGvo;
    }

    
    @Column(name="nome", nullable=false, length=50)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sobreNome", nullable=false, length=50)
    public String getSobreNome() {
        return this.sobreNome;
    }
    
    public void setSobreNome(String sobreNome) {
        this.sobreNome = sobreNome;
    }

    
    @Column(name="cpf", nullable=false, length=14)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    
    @Column(name="endereco", nullable=false, length=60)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="pais", nullable=false, length=60)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="bairro", nullable=false, length=60)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", nullable=false, length=60)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="telefone", length=25)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="celular", nullable=false, length=25)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="desconto", nullable=false, length=100)
    public String getDesconto() {
        return this.desconto;
    }
    
    public void setDesconto(String desconto) {
        this.desconto = desconto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clienteGvo")
    public Set getComprasGvos() {
        return this.comprasGvos;
    }
    
    public void setComprasGvos(Set comprasGvos) {
        this.comprasGvos = comprasGvos;
    }




}


