package bean;
// Generated 21/09/2023 21:37:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JogosGvo generated by hbm2java
 */
@Entity
@Table(name="jogos_gvo"
    ,catalog="guilherme_osterberg2"
)
public class JogosGvo  implements java.io.Serializable {


     private int idJogosGvo;
     private PatrocinadoresGvo patrocinadoresGvo;
     private PlataformaGvo plataformaGvo;
     private String nomeGvo;
     private Double precoGvo;
     private String versaoFisicaGvo;
     private Date dataLancamentoGvo;

    public JogosGvo() {
    }

    public JogosGvo(int idJogosGvo, PatrocinadoresGvo patrocinadoresGvo, PlataformaGvo plataformaGvo, String nomeGvo, Double precoGvo, String versaoFisicaGvo, Date dataLancamentoGvo) {
       this.idJogosGvo = idJogosGvo;
       this.patrocinadoresGvo = patrocinadoresGvo;
       this.plataformaGvo = plataformaGvo;
       this.nomeGvo = nomeGvo;
       this.precoGvo = precoGvo;
       this.versaoFisicaGvo = versaoFisicaGvo;
       this.dataLancamentoGvo = dataLancamentoGvo;
    }
   
     @Id 

    
    @Column(name="idJogos_gvo", unique=true, nullable=false)
    public int getIdJogosGvo() {
        return this.idJogosGvo;
    }
    
    public void setIdJogosGvo(int idJogosGvo) {
        this.idJogosGvo = idJogosGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Patrocinadores_gvo", nullable=false)
    public PatrocinadoresGvo getPatrocinadoresGvo() {
        return this.patrocinadoresGvo;
    }
    
    public void setPatrocinadoresGvo(PatrocinadoresGvo patrocinadoresGvo) {
        this.patrocinadoresGvo = patrocinadoresGvo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fk_Plataforma_gvo", nullable=false)
    public PlataformaGvo getPlataformaGvo() {
        return this.plataformaGvo;
    }
    
    public void setPlataformaGvo(PlataformaGvo plataformaGvo) {
        this.plataformaGvo = plataformaGvo;
    }

    
    @Column(name="nome_gvo", nullable=false, length=50)
    public String getNomeGvo() {
        return this.nomeGvo;
    }
    
    public void setNomeGvo(String nomeGvo) {
        this.nomeGvo = nomeGvo;
    }

    
    @Column(name="preco_gvo", nullable=false, precision=10)
    public Double getPrecoGvo() {
        return this.precoGvo;
    }
    
    public void setPrecoGvo(Double precoGvo) {
        this.precoGvo = precoGvo;
    }

    
    @Column(name="versaoFisica_gvo", nullable=false, length=50)
    public String getVersaoFisicaGvo() {
        return this.versaoFisicaGvo;
    }
    
    public void setVersaoFisicaGvo(String versaoFisicaGvo) {
        this.versaoFisicaGvo = versaoFisicaGvo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataLancamento_gvo", nullable=false, length=10)
    public Date getDataLancamentoGvo() {
        return this.dataLancamentoGvo;
    }
    
    public void setDataLancamentoGvo(Date dataLancamentoGvo) {
        this.dataLancamentoGvo = dataLancamentoGvo;
    }




}


