package bean;
// Generated 21/09/2023 21:37:26 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlataformaGvo generated by hbm2java
 */
@Entity
@Table(name="plataforma_gvo"
    ,catalog="guilherme_osterberg2"
)
public class PlataformaGvo  implements java.io.Serializable {


     private int idPlataformaGvo;
     private String plataformaGvo;
     private String consolePlatGvo;
     private Set jogosGvos = new HashSet(0);

    public PlataformaGvo() {
    }

	
    public PlataformaGvo(int idPlataformaGvo, String plataformaGvo, String consolePlatGvo) {
        this.idPlataformaGvo = idPlataformaGvo;
        this.plataformaGvo = plataformaGvo;
        this.consolePlatGvo = consolePlatGvo;
    }
    public PlataformaGvo(int idPlataformaGvo, String plataformaGvo, String consolePlatGvo, Set jogosGvos) {
       this.idPlataformaGvo = idPlataformaGvo;
       this.plataformaGvo = plataformaGvo;
       this.consolePlatGvo = consolePlatGvo;
       this.jogosGvos = jogosGvos;
    }
   
     @Id 

    
    @Column(name="idPlataforma_gvo", unique=true, nullable=false)
    public int getIdPlataformaGvo() {
        return this.idPlataformaGvo;
    }
    
    public void setIdPlataformaGvo(int idPlataformaGvo) {
        this.idPlataformaGvo = idPlataformaGvo;
    }

    
    @Column(name="plataforma_gvo", nullable=false, length=50)
    public String getPlataformaGvo() {
        return this.plataformaGvo;
    }
    
    public void setPlataformaGvo(String plataformaGvo) {
        this.plataformaGvo = plataformaGvo;
    }

    
    @Column(name="ConsolePlat_gvo", nullable=false, length=50)
    public String getConsolePlatGvo() {
        return this.consolePlatGvo;
    }
    
    public void setConsolePlatGvo(String consolePlatGvo) {
        this.consolePlatGvo = consolePlatGvo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="plataformaGvo")
    public Set getJogosGvos() {
        return this.jogosGvos;
    }
    
    public void setJogosGvos(Set jogosGvos) {
        this.jogosGvos = jogosGvos;
    }




}


